routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DepositController;
use App\Http\Controllers\WithdrawController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');
// Route::get('/dashboard', [DepartmentController::class, 'index']);
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [DepartmentController::class, 'index'])->name('dashboard');

Route::group(['middleware' => ['auth']], function () { 
    Route::resource('departments',DepartmentController::class);
    Route::resource('deposits',DepositController::class);
    Route::get('/deposits/mainindex/{id}',[DepositController::class,'mainindex'])->name('deposits.mainindex');
    Route::get('/deposits/maincreate/{id}',[DepositController::class,'maincreate'])->name('deposits.maincreate');

    Route::get('withdraws/main/{id}',[WithdrawController::class,'index'])->name('withdraws.main');
    Route::get('withdraws/main/create/{id}',[WithdrawController::class,'create'])->name('withdraws.main.create');
    Route::resource('withdraws',WithdrawController::class);
    Route::get('withdraws/word/{id}',[WithdrawController::class,'word'])->name('withdraws.word');




    Route::get('challans/search/',[DepositController::class,'search'])->name('challan.search');
    // Route::post('/deposits/save',[DepositController::class,'store'])->name('deposits.store');
    // Route::delete('/deposits/delete/{id}',[DepositController::class,'destroy'])->name('deposits.destroy');
    // Route::post('departments/store',[DepartmentController::class,'store'])->name('departments.store');
    Route::get('date/search/',[DepositController::class,'date_search'])->name('date.search');
    Route::get('memo/search/',[WithdrawController::class,'memo_search'])->name('memo.search');
});

app/Models/Deposit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Deposit extends Model
{
    use HasFactory;

    protected $fillable = [
        'particulars','depo_d3', 'department', 'challan_number','create_date','challan_amount','release_amount','withdrawn_amount','balance','department_id','balance',
        'treasury',
    ];
}

app/Http/Controllers/DepositController.php
<?php

namespace App\Http\Controllers;
use App\Models\Department;
use App\Models\Deposit;
use Illuminate\Http\Request;
use Redirect;
use Illuminate\Support\Facades\DB;
class DepositController extends Controller
{
    public function mainindex($id)
    {
        $department=Department::findOrFail($id);
        $deposits=Deposit::where('department_id',$id)->paginate(7);
        return view('deposit.index',compact('department','deposits'));
    }

    public function maincreate($id)
    {
        $department=Department::findOrFail($id);
        return view('deposit.create',compact('department'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $request->validate([
            'particulars'=>'required', 
            'department'=>'required',
            'challan_number'=>'required',
            'create_date'=>'required',
            'challan_amount'=>'required',
            'withdrawn_amount'=>'required',
            'balance'=>'required',
            'department_id'=>'required',
            'treasury'=>'required',
            'depo_d3'=>'required',
        ]);

        $timestamp = strtotime($request->create_date);

        //Convert it to DD-MM-YYYY
        $dmy = date("d-m-Y", $timestamp); 

        $search=Deposit::where('treasury',$request->treasury)->get();
        foreach($search as $s)
        {
            if($s->challan_number==$request->challan_number && $s->create_date==$dmy)
            {
                return redirect()->back() ->with('alert', 'Cannot have the same date, challan no. and Treasury!');
            }
            
        }
       
        // if() 
        //     return redirect()->back() ->with('alert', 'Cannot have the same date, challan no. and Treasury!');
        // else
        //     dd("Nothing");
        


        // dd($request);
        Deposit::create([
            'particulars'=>$request->particulars, 
            'depo_d3'=>$request->depo_d3,
            'department'=>$request->department,
            
            'challan_number'=>$request->challan_number,
            'create_date'=>$dmy,
            'challan_amount'=>$request->challan_amount,
            'balance'=>$request->balance,
            'withdrawn_amount'=>$request->withdrawn_amount,
            'department_id'=>$request->department_id,
            'treasury'=>$request->treasury,
            
        ]);
            
        $department=Department::where('id',$request->department_id)->first();
        // dd($department);
        // $deposit=Deposit::where('department_id',$id)->latest()->first();
        // dd($deposit->id);
        $deposits=Deposit::where('department_id',$request->department_id)->paginate(7);
        return view('deposit.index',compact('department','deposits'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $deposit=Deposit::findOrFail($id);
        
        return view('deposit.edit', compact('deposit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'particulars'=>'required', 
            'department'=>'required',
            'challan_number'=>'required',
            'create_date'=>'required',
            'challan_amount'=>'required',
            'treasury'=>'required',
            'balance'=>'required',
            'withdrawn_amount'=>'required',
            'department_id'=>'required',
            
        ]);

        $timestamp = strtotime($request->create_date);

        //Convert it to DD-MM-YYYY
        $dmy = date("d-m-Y", $timestamp);

        $update = [
            'particulars'=>$request->particulars, 
            'department'=>$request->department,
            'challan_number'=>$request->challan_number,
            'create_date'=>$dmy,
            'challan_amount'=>$request->challan_amount,
            'balance'=>$request->balance,
            'withdrawn_amount'=>$request->withdrawn_amount,
            'department_id'=>$request->department_id,
            'treasury'=>$request->treasury,
        ];
        Deposit::where('id',$id)->update($update);

        
        // dd($request->department_id);
        $department=Department::where('id',$request->department_id)->first();
        // dd($department->department_name);
        $deposits=Deposit::where('department_id',$request->department_id)->paginate(7);
        return view('deposit.index',compact('department','deposits'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $depoDept=Deposit::where('id',$id)->pluck('department_id');
        $departments=Department::all();
        Deposit::where('id',$id)->delete();
        
        

       
        return redirect()->route('dashboard',compact('departments'));
    }

    public function search(Request $request)
    {
        $deposits=Deposit::where('challan_number',$request->c_number)->firstOrFail();
        // dd($deposits->id);
        $department=Department::where('id',$deposits->department_id)->first();
        // dd($department->name);
        return view('deposit.search',compact('department','deposits'));
        // dd($deposits->department_id);
    }


    public function date_search(Request $request)
    {
        $timestamp = strtotime($request->d_date);
        $dmy = date("d-m-Y", $timestamp);
        // dd($dmy);
        $deposits=Deposit::where('create_date',$dmy)->get();
        
        // dd($deposits);
        return view('deposit.search_by_date',compact('deposits'));
    }



    
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/deposit/edit.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8" >
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <form class="m-2 border" method="POST" action="{{ route('deposits.update',$deposit->id) }}">
                    @csrf
                    @method('PATCH')
                    <div class="m-5">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Particulars</label>
                                        <input type="text" class="form-control" name="particulars" value="{{ $deposit->particulars }}">
                                        <div class="form-text">Enter particulars</div>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Department Name</label>
                                        <input name="department" type="text" class="form-control" value="{{ $deposit->department  }}">
                                    </div>
                                </div>
                              
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Challan Date</label>
                                        <input type="text" class="form-control" name="create_date" value="{{ $deposit->create_date }}" required>
                                        <div class="form-text">Enter Challan Date</div>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Challan number</label>
                                        <input type="text" class="form-control" name="challan_number" value="{{ $deposit->challan_number }}">
                                        <div class="form-text">Enter Challan number</div>
                                    </div>
                                </div>
                              
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Challan Amount</label>
                                        <input type="text" class="form-control" name="challan_amount" value="{{ $deposit->challan_amount }}">
                                        <div class="form-text">Enter Challan Amount</div>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Withdrawn amount</label>
                                        <input type="text" class="form-control" name="withdrawn_amount" value="{{ $deposit->withdrawn_amount }}">
                                        <div class="form-text">Enter withdrawn amount</div>
                                    </div>
                                </div>
                              
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Balance</label>
                                        <input type="text" class="form-control" name="balance" value="{{ $deposit->balance }}">
                                        <div class="form-text">Enter Balance</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm">
                            <div class="mb-3 ml-2 mr-2">
                                <label class="form-label">Treasury</label>
                                <input type="text" class="form-control form-control{{($errors->first('treasury') ? 'is-dangerous' : '')}}" name="treasury" id="treasury" value="{{ $deposit->treasury }}"></textarea>
                                <div class="form-text">Enter treasury</div>
                                <p class="help" style="color:red">{{ $errors->first('treasury') }}</p>
                            </div>
                        </div>
                        

                       
                        <input type="hidden" value="{{ $deposit->department_id }}" class="ml-2 mr-2" name="department_id"><br>
                        <button type="submit" class="btn btn-primary ml-2 mr-2">Submit</button>
                    </div>

                    
                    
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/deposit/index.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-8xl mx-auto sm:px-6 lg:px-8" style="padding-top:20px">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div style="display: flex;justify-content: space-between">
                    <h3 class="ml-4 mt-3" style="color: rgba(59, 130, 246, 0.5)">{{ $department->department_name}}</h3>
                    <a class="btn btn-primary btn-sm mb-3 float-right mt-3 mr-2" href="{{ route('deposits.maincreate',$department->id) }}">New Challan</a>
                </div>
                
                <table class="table-fixed table-bordered m-3 container-fluid ">
                    <thead>
                        <tr>
                            <th>Particulars</th>
                            <th width="100px">Type</th>
                            <th>Department</th>
                            <th width="100px">Challan No</th>
                            <th width="100px">Date</th>
                            <th width="130px">Challan Amount</th>
                            <th width="155px">Withdrawn amount</th>
                            <th width="100px">Balance</th>
                            <th>Treasury</th>
                            <th class="ml-3" width="160px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            @foreach ($deposits as $deposit)
                            <tr>
                                <td scope="row">{{ $deposit->particulars }}</td>
                                <td>{{ $deposit->depo_d3 }}</div></td>
                                <td><div class="ml-1" style="font-size:15px">{{ $deposit->department }}</td>
                                <td style="font-size:15px">{{ $deposit->challan_number }}</div></td>
                                <td style="font-size:15px">{{ $deposit->create_date }}</td>
                                <td>
                                    <div class="ml-1">{{ $deposit->challan_amount }}</div>
                                </td>
                                <td>
                                    <div class="ml-1">{{ $deposit->withdrawn_amount }}</div>
                                </td>
                                
                                <td>{{ $deposit->balance }}</td>
                                <td>
                                    <div class="ml-1">{{ $deposit->treasury }}</div>
                                </td>
                                <td style="display: flex; justify-content:start">
                                    <div>
                                        <a class="btn btn-outline-success btn-sm mt-2" href="{{ route('deposits.edit',$deposit->id) }}"> 
                                            <i class="fas fa-pen-square fa-lg float-center icon_at_center" ></i>
                                        </a>
                                    </div>
                                    <div>
                                        <form action="{{ route('deposits.destroy',$deposit->id) }}" method="POST" class="ml-2 mt-2">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure?')">
                                                <i class="fas fa-calendar-times fa-lg icon_at_center">
                                                </i>
                                            </button>
                                        </form>
                                    </div>
                                    <div>
                                        <a type="button" class="btn btn-outline-primary btn-sm mt-2 ml-2" href="{{ route('withdraws.main',$deposit->id) }}">
                                           <i class="fas fa-rupee-sign fa-lg icon_at_center"></i>
                                          
                                        </a>
                                    </div>
                                </td>    
                            </tr>
                            @endforeach
                        </tr>
                      
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/deposit/search.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-8xl mx-auto sm:px-6 lg:px-8" style="padding-top:20px">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div style="display: flex;justify-content: space-between">
                    <h3 class="ml-4 mt-3" style="color: rgba(59, 130, 246, 0.5)">{{ $department->name}}</h3>
                    {{-- <a class="btn btn-primary btn-sm mb-3 float-right mt-3 mr-2" href="{{ route('deposits.maincreate',$department->id) }}">New Transaction</a> --}}
                </div>
                
                <table class="table-fixed table-bordered m-3 container-fluid ">
                    <thead>
                        <tr>
                            <th>Particulars</th>
                            <th>Department</th>
                            <th>Challan No</th>
                            <th>Date</th>
                            <th>Challan Amount</th>
                            <th>Withdrawn amount</th>
                            <th>Balance</th>
                            <th>Treasury</th>
                            <th class="ml-3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {{-- @foreach ($deposits as $deposit) --}}
                            <tr>
                                <td scope="row">{{ $deposits->particulars }}</td>
                                <td><div class="ml-1" style="font-size:15px">{{ $deposits->department }}</td>
                                <td style="font-size:15px">{{ $deposits->challan_number }}</div></td>
                                <td style="font-size:15px">{{ $deposits->create_date }}</td>
                                <td>
                                    <div class="ml-1">{{ $deposits->challan_amount }}</div>
                                </td>
                                <td>
                                    <div class="ml-1">{{ $deposits->withdrawn_amount }}</div>
                                </td>
                                
                                <td>{{ $deposits->balance }}</td>
                                <td>{{ $deposits->treasury }}</td>
                                <td style="display: flex; justify-content:start">
                                    <div>
                                        <a class="btn btn-outline-success btn-sm mt-2" href="{{ route('deposits.edit',$deposits->id) }}"> 
                                            <i class="fas fa-pen-square fa-lg float-center icon_at_center" ></i>
                                        </a>
                                    </div>
                                    <div>
                                        <form action="{{ route('deposits.destroy',$deposits->id) }}" method="POST" class="ml-2 mt-2">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure?')">
                                                <i class="fas fa-calendar-times fa-lg icon_at_center">
                                                </i>
                                            </button>
                                        </form>
                                    </div>
                                    <div>
                                        <a type="button" class="btn btn-outline-primary btn-sm mt-2 ml-2" href="{{ route('withdraws.main',$deposits->id) }}">
                                           <i class="fas fa-rupee-sign fa-lg icon_at_center"></i>
                                          
                                        </a>
                                    </div>
                                </td>    
                            </tr>
                            {{-- @endforeach --}}
                        </tr>
                      
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/deposit/search_by_date.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-8xl mx-auto sm:px-6 lg:px-8" style="padding-top:20px">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div style="display: flex;justify-content: space-between">
                    
                </div>
                
                <table class="table-fixed table-bordered m-3 container-fluid ">
                    <thead>
                        <tr>
                            <th>Particulars</th>
                            <th>Department</th>
                            <th>Challan No</th>
                            <th>Date</th>
                            <th>Challan Amount</th>
                            <th>Withdrawn amount</th>
                            <th>Balance</th>
                            <th>Treasury</th>
                            <th class="ml-3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            @foreach ($deposits as $deposit)
                            <tr>
                                <td scope="row">{{ $deposit->particulars }}</td>
                                <td><div class="ml-1" style="font-size:15px">{{ $deposit->department }}</td>
                                <td style="font-size:15px">{{ $deposit->challan_number }}</div></td>
                                <td style="font-size:15px">{{ $deposit->create_date }}</td>
                                <td>
                                    <div class="ml-1">{{ $deposit->challan_amount }}</div>
                                </td>
                                <td>
                                    <div class="ml-1">{{ $deposit->withdrawn_amount }}</div>
                                </td>
                                
                                <td>{{ $deposit->balance }}</td>
                                <td>{{ $deposit->treasury }}</td>
                                <td style="display: flex; justify-content:start">
                                    <div>
                                        <a class="btn btn-outline-success btn-sm mt-2" href="{{ route('deposits.edit',$deposit->id) }}"> 
                                            <i class="fas fa-pen-square fa-lg float-center icon_at_center" ></i>
                                        </a>
                                    </div>
                                    <div>
                                        <form action="{{ route('deposits.destroy',$deposit->id) }}" method="POST" class="ml-2 mt-2">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure?')">
                                                <i class="fas fa-calendar-times fa-lg icon_at_center">
                                                </i>
                                            </button>
                                        </form>
                                    </div>
                                    <div>
                                        <a type="button" class="btn btn-outline-primary btn-sm mt-2 ml-2" href="{{ route('withdraws.main',$deposit->id) }}">
                                           <i class="fas fa-rupee-sign fa-lg icon_at_center"></i>
                                          
                                        </a>
                                    </div>
                                </td>    
                            </tr>
                            @endforeach
                        </tr>
                      
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
</x-app-layout>