routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DepositController;
use App\Http\Controllers\WithdrawController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');
// Route::get('/dashboard', [DepartmentController::class, 'index']);
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [DepartmentController::class, 'index'])->name('dashboard');

Route::group(['middleware' => ['auth']], function () { 
    Route::resource('departments',DepartmentController::class);
    Route::resource('deposits',DepositController::class);
    Route::get('/deposits/mainindex/{id}',[DepositController::class,'mainindex'])->name('deposits.mainindex');
    Route::get('/deposits/maincreate/{id}',[DepositController::class,'maincreate'])->name('deposits.maincreate');

    Route::get('withdraws/main/{id}',[WithdrawController::class,'index'])->name('withdraws.main');
    Route::get('withdraws/main/create/{id}',[WithdrawController::class,'create'])->name('withdraws.main.create');
    Route::resource('withdraws',WithdrawController::class);
    Route::get('withdraws/word/{id}',[WithdrawController::class,'word'])->name('withdraws.word');




    Route::get('challans/search/',[DepositController::class,'search'])->name('challan.search');
    // Route::post('/deposits/save',[DepositController::class,'store'])->name('deposits.store');
    // Route::delete('/deposits/delete/{id}',[DepositController::class,'destroy'])->name('deposits.destroy');
    // Route::post('departments/store',[DepartmentController::class,'store'])->name('departments.store');
    Route::get('date/search/',[DepositController::class,'date_search'])->name('date.search');
    Route::get('memo/search/',[WithdrawController::class,'memo_search'])->name('memo.search');
});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'abbreviation',
    ];
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;
use App\Models\Department;
use Illuminate\Http\Request;
use App\Http\Controllers\Redirect;
class DepartmentController extends Controller
{
    public function index()
    {
        $departments=Department::orderBy('name')->get();

        return view('dashboard',compact('departments'));
    }

    public function create()
    {
        return view('department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->name);
        $request->validate([
            'name' => 'required',
            'abbreviation'=>'required|unique:departments',
            ]);
            Department::create($request->all());
            
            $departments=Department::paginate(15);
            
            return view('dashboard',compact('departments'))->with('success','New Department is added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $department=Department::findOrFail($id);
        
        return view('department.edit', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'abbreviation'=>'required|unique:departments',
            ]);
        $update = ['name' => $request->name, 'abbreviation'=>$request->abbreviation];
        Department::where('id',$id)->update($update);

       
        $departments=Department::all();
        return redirect()->route('departments.index',compact('departments'))
            ->with('success','Department is updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Department::where('id',$id)->delete();
        return back()->with('delete','Department is Deleted !');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/department/create.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8" style="padding-top:100px">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <form method="POST"   action="{{ route('departments.store') }}" class="m-5">
                   
                    @csrf
                    @method('POST')
                    <div class="form-group">
                        <label for="exampleInputEmail1">Department Name</label>
                        <input type="text" class="form-control" name="name">
                        <small id="emailHelp" class="form-text text-muted">Enter department name and click 'Add Button'</small>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Abbreviation</label>
                        <input type="text" class="form-control" name="abbreviation">
                        <small id="emailHelp" class="form-text text-muted">Enter abbreviation and click 'Add Button'</small>
                    </div>
                    {{-- <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1">
                    </div> --}}
                    {{-- <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div> --}}
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/department/edit.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8" style="padding-top:100px">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <form method="POST" action="{{ route('departments.update',$department->id) }}" class="m-5">
                   
                    @csrf
                    @method('PATCH')
                    <div class="form-group">
                        <label for="exampleInputEmail1">Department Name</label>
                        <input type="text" class="form-control"  value="{{ $department->name }}" name="name"required>
                        <small id="emailHelp" class="form-text text-muted">Edit department name and click 'Update Button'</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Abbreviation</label>
                        <input type="text" class="form-control"  value="{{ $department->abbreviation }}" required name="abbreviation">
                        <small id="emailHelp" class="form-text text-muted">Enter abbreviation and click 'Add Button'</small>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>