routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DepositController;
use App\Http\Controllers\WithdrawController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');
// Route::get('/dashboard', [DepartmentController::class, 'index']);
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [DepartmentController::class, 'index'])->name('dashboard');

Route::group(['middleware' => ['auth']], function () { 
    Route::resource('departments',DepartmentController::class);
    Route::resource('deposits',DepositController::class);
    Route::get('/deposits/mainindex/{id}',[DepositController::class,'mainindex'])->name('deposits.mainindex');
    Route::get('/deposits/maincreate/{id}',[DepositController::class,'maincreate'])->name('deposits.maincreate');

    Route::get('withdraws/main/{id}',[WithdrawController::class,'index'])->name('withdraws.main');
    Route::get('withdraws/main/create/{id}',[WithdrawController::class,'create'])->name('withdraws.main.create');
    Route::resource('withdraws',WithdrawController::class);
    Route::get('withdraws/word/{id}',[WithdrawController::class,'word'])->name('withdraws.word');




    Route::get('challans/search/',[DepositController::class,'search'])->name('challan.search');
    // Route::post('/deposits/save',[DepositController::class,'store'])->name('deposits.store');
    // Route::delete('/deposits/delete/{id}',[DepositController::class,'destroy'])->name('deposits.destroy');
    // Route::post('departments/store',[DepartmentController::class,'store'])->name('departments.store');
    Route::get('date/search/',[DepositController::class,'date_search'])->name('date.search');
    Route::get('memo/search/',[WithdrawController::class,'memo_search'])->name('memo.search');
});

app/Models/Withdraw.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Withdraw extends Model
{
    use HasFactory;
    protected $fillable = [
        'release_amount','release_date','balance','deposit_id',
    ];
}

app/Http/Controllers/WithdrawController.php
<?php

namespace App\Http\Controllers;

use App\Models\Withdraw;
use App\Models\Deposit;
use App\Models\Department;
use Illuminate\Http\Request;
use DB;

class WithdrawController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        $withdraws=Withdraw::where('deposit_id',$id)->orderBy('created_at','DESC')->get();
        $deposit=Deposit::find($id);
        $withdrawn=Withdraw::where('deposit_id',$id)->get();
        return view('withdraw.index',compact('withdraws','deposit','withdrawn'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $deposit=Deposit::find($id);
        
        // dd($withdraw->id);
        $withdraw=Withdraw::where('deposit_id',$id)->latest()->first();
        if($deposit->withdrawn_amount==$deposit->challan_amount)
        {
           return view('withdraw.error');
        }
        else
        {
            return view('withdraw.create',compact('deposit','withdraw'));
        }
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'release_amount'=>'required',
            'release_date'=>'required',
            'balance'=>'required',
            'deposit_id'=>'required',
        ]);
        $deposit=Deposit::find($request->deposit_id);
        $department=Department::find($deposit->department_id);
        $withdrawCount=Withdraw::count();
        $count=$withdrawCount+1;
        do {
            $release_memo = $count.'/'.$department->abbreviation;
         } while ( DB::table( 'withdraws' )->where( 'release_memo', $release_memo )->exists() );



        $timestamp = strtotime($request->release_date);
        //Convert it to DD-MM-YYYY
        $dmy = date("d-m-Y", $timestamp);

        $withdrawsave=new Withdraw;
        $withdrawsave->release_amount=$request->release_amount;
        $withdrawsave->release_date=$dmy;
        $withdrawsave->balance=$request->balance;
        $withdrawsave->deposit_id=$request->deposit_id;
        $withdrawsave->balance=$request->balance;
        $withdrawsave->release_memo=$release_memo;
        $withdrawsave->save();
       


        $deposit=Deposit::find($request->deposit_id);
        $total_withdrawn=Withdraw::where('deposit_id',$request->deposit_id)->pluck('release_amount')->sum();
        $a=$deposit->challan_amount;
        $b=$deposit->withdrawn_amount+$request->release_amount;
        $balance=(int)$a-(int)$b;
    
        Deposit::where('id',$request->deposit_id)->update(['withdrawn_amount'=>$total_withdrawn, 'balance'=>$balance]);
        $withdraws=Withdraw::where('deposit_id',$request->deposit_id);
        return redirect()->route('withdraws.main',$request->deposit_id)->with( ['deposit' => $deposit,'withdraws' => $deposit] )->with('status', 'withdraw updated!');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Withdraw  $withdraw
     * @return \Illuminate\Http\Response
     */
    public function show(Withdraw $withdraw)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Withdraw  $withdraw
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $withdraw=Withdraw::find($id);
        $deposit=Deposit::where('id',$withdraw->deposit_id)->first();
        return view('withdraw.edit',compact('withdraw','deposit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Withdraw  $withdraw
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'release_amount'=>'required',
            'release_date'=>'required',
            'balance'=>'required',
            'deposit_id'=>'required',
            'release_memo'=>'required'
        ]);
        $timestamp = strtotime($request->release_date);
        //Convert it to DD-MM-YYYY
        $dmy = date("d-m-Y", $timestamp);

        $update = [
            'release_amount'=>$request->release_amount, 
            'release_date'=>$dmy,
            'balance'=>$request->balance,
            'deposit_id'=>$request->deposit_id,
            'release_memo'=>$request->release_memo,
        ];
        $withdraw=Withdraw::where('id',$id);
        $withdraw->update($update);

        $withdraws=Withdraw::where('deposit_id',$request->deposit_id)->orderBy('created_at','DESC')->get();
        $deposit=Deposit::find($request->deposit_id);
        $withdrawn=Withdraw::where('deposit_id',$request->deposit_id)->get();
        return view('withdraw.index',compact('withdraws','deposit','withdrawn'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Withdraw  $withdraw
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $withdraw=Withdraw::findOrFail($id);
        $deposit=Deposit::find($withdraw->deposit_id);

        $deposit_balance=$deposit->balance+$withdraw->release_amount;
        $deposit_withdrawn_amount=$deposit->withdrawn_amount-$withdraw->release_amount;

        // dd($deposit_balance);
        $deposit->update(['withdrawn_amount'=>$deposit_withdrawn_amount, 'balance'=>$deposit_balance]);
        $withdraw->delete();

        return back()->with('delete','Withdraw detail is Deleted !');
    }
    

    public function word($id)
    {
        
        $withdraw=Withdraw::findOrFail($id);
        $deposit=Deposit::findOrFail($withdraw->deposit_id);
        $dept=Department::where('id',$deposit->department_id)->first();
        $phpWord = new \PhpOffice\PhpWord\PhpWord();

        $memo= htmlspecialchars($withdraw->release_memo);
        $release_date=htmlspecialchars($withdraw->release_date);
        $section = $phpWord->addSection();
        $phpWord->setDefaultFontSize(13);
        $particulars=htmlspecialchars($deposit->particulars);
        $description = "\t \t \t \t ID.NO.FIN(EA): $memo <w:br/>\t \t \t \t $release_date <w:br/>
        \t \t \t \t \t \t \t \t 
                        <w:br/>
                        <w:br/>
                        Finance Department (EA) agrees to the proposal of  $dept->name Department  for release of fund amounting to Rs.$withdraw->release_amount (Rupees ____________________________________________________ only) 
                        for $particulars from K.Deposit/Deposit-III under Challan No.$deposit->challan_number Dt.$deposit->create_date .
                        <w:br/>
                        <w:br/>
                        <w:br/>
                        <w:br/>
                        <w:br/>
                                                                             Under Secretary,<w:br/>
                                                                            Finance Deptt.(EA)<w:br/><w:br/>
Secretary, <w:br/>
$dept->name Deptt.<w:br/><w:br/><w:br/>
Copy to:<w:br/>
        The Treasury Officer, $deposit->treasury for information.
        <w:br/>
        <w:br/>
        <w:br/>
        <w:br/>
        <w:br/>
                                                                             Under Secretary,<w:br/>
                                                                            Finance Dept. (EA)                                             
                                                                            
                        ";


       
        $section->addText($description);


        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
        try {
            $objWriter->save(storage_path($deposit->challan_number.$withdraw->release_date.'.doc'));
        } catch (Exception $e) {
        }


        return response()->download(storage_path($deposit->challan_number.$withdraw->release_date.'.doc'));
    }



    public function memo_search(Request $request)
    {
        $withdraw=Withdraw::where('release_memo',$request->memo)->firstOrFail();
        $deposit=Deposit::find($withdraw->deposit_id);
        return view('withdraw.memoSearch',compact('withdraw','deposit'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/withdraw/create.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8" >
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <form class="m-2 border" method="POST" action="{{ route('withdraws.store') }}">
                    @csrf
                    @method('POST')
                    <div class="m-5">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Release Amount</label>
                                        <input type="text" class="form-control form-control{{($errors->first('release_amount') ? 'is-dangerous' : '')}}" id="RA" name="release_amount" onkeyup="sum();">
                                        <div class="form-text">Enter release_amount</div>
                                        <p class="help" style="color:red">{{ $errors->first('release_amount') }}</p>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Release Date</label>
                                        <input type="date" class="form-control form-control{{($errors->first('release_date') ? 'is-dangerous' : '')}}" name="release_date">
                                        <div class="form-text">Enter release date</div>
                                        <p class="help" style="color:red">{{ $errors->first('release_date') }}</p>
                                    </div>
                                </div>
                              
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Challan Remaining</label>
                                        <input type="text" class="form-control form-control{{($errors->first('challan_amount') ? 'is-dangerous' : '')}}" id="CA" name="challan_amount" value={{ $deposit->balance }}>
                                        <div class="form-text">Challan Remaining</div>
                                        <p class="help" style="color:red">{{ $errors->first('challan_amount') }}</p>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="mb-3 ">
                                        <label class="form-label">Balance</label>
                                        <input type="text" class="form-control" id="BA" name="balance" required>
                                       
                                       
                                    </div>
                                    <script>
                                        function sum() {
                                            var txtFirstNumberValue = document.getElementById('CA').value;
                                            var txtSecondNumberValue = document.getElementById('RA').value;
                                            var result = parseInt(txtFirstNumberValue) - parseInt(txtSecondNumberValue);
                                            if (!isNaN(result)) {
                                                document.getElementById('BA').value = result;
                                            }
                                        }
                                    </script>
                                </div>
                              
                            </div>
                        </div>
                        
                       
                       
                        
                        

                        
                       
                        
                        
                        <input type="hidden" value="{{ $deposit->id }}" class="ml-2 mr-2" name="deposit_id"><br>
                        <button type="submit" class="btn btn-primary ml-2 mr-2">Submit</button>
                    </div>

                    
                    
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/withdraw/index.blade.php
<x-app-layout>
    {{-- <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot> --}}
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <div class="py-12">
        <div class="max-w-8xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="pl-3 pr-3 mt-3 mb-5">
                    <div class="grid grid-cols-3 gap-4">
                        <div class="...">
                            <!--Card 1-->
                            <div class="max-w-lg rounded overflow-hidden shadow-lg">
                                
                                <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">{{ $deposit->particulars }}</div>
                                <p class="text-gray-700 text-base">
                                    <div class="grid grid-cols-6 gap-4">
                                       
                                        <div class="col-start-1 col-end-5 ...">Department</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->department }}</div>
                                        <div class="col-start-1 col-end-5 ...">Challan No.</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->challan_number }}</div>

                                        <div class="col-start-1 col-end-5 ...">Date</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->create_date }}</div>
                                        <div class="col-start-1 col-end-5 ...">Challan amount</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->challan_amount }}</div>

                                        <div class="col-start-1 col-end-5 ...">Withdrawn Amount</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->withdrawn_amount }}</div>
                                        
                                        <div class="col-start-1 col-end-5 ...">Balance</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->balance }}</div>

                                        <div class="col-start-1 col-end-5 ...">Treasury</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->treasury }}</div>
                                    </div>
                                </p>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-span-2 ...">
                            <a class="btn btn-primary btn-sm mb-3 float-right" href="{{ route('withdraws.main.create',$deposit->id) }}">Withdraw</a>
                            <table class="table table-hover table-bordered align-middle">
                                <thead>
                                    <tr>
                                        <th>SI</th>
                                        <th class="w-1/4">Release Memo</th>
                                        <th class="w-1/4">Release Amount</th>
                                        <th class="w-1/4">Release Date</th>
                                       
                                        <th class="w-1/4">Balance</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $i=1
                                    @endphp
                                    @foreach ($withdraws as $withdraw)
                                        
                                    <tr>
                                        <th scope="row">
                                            @php
                                                echo $i++;
                                            @endphp    
                                        </th>
                                        <td>{{ $withdraw->release_memo }}</td>
                                        <td>{{ $withdraw->release_amount }}</td>
                                        <td>{{ $withdraw->release_date }}</td>
                                       
                                        <td>{{ $withdraw->balance }}</td>
                                        <td >
                                            <div class="grid grid-flow-col md:grid-flow-col">
                                                {{-- <div class="...">
                                                    <a type="button" class="btn btn-outline-success btn-sm" href="{{ route('withdraws.edit',$withdraw->id) }}"> 
                                                        <i class="fas fa-pen-square " ></i>
                                                    </a>
                                                </div> --}}
                                                <div class="...">
                                                    <form action="{{ route('withdraws.destroy',$withdraw->id) }}" method="POST" class="ml-2 mr-2">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure?')">
                                                        <i class="fas fa-calendar-times">
                                                        </i>
                                                    </button>
                                                    </form>
                                                   
                                                </div>
                                                <div>
                                                    <a type="button" class="btn btn-outline-success btn-sm" href="{{ route('withdraws.word',$withdraw->id) }}"> 
                                                        <i class="far fa-file-word" > </i>
                                                    </a>
                                                </div>
                                               
                                            </div>
                                            
                                        
                                            
                                            
                                           
                                        </td>
                                    
                                        
                                            
                                    </tr>
                                    @endforeach
                                    
                                
                                
                                </tbody>
                            </table>
                        </div>
                    </div>    
                    
                </div>  
                
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/withdraw/memoSearch.blade.php
<x-app-layout>
    {{-- <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot> --}}
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <div class="py-12">
        <div class="max-w-8xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="pl-3 pr-3 mt-3 mb-5">
                    <div class="grid grid-cols-3 gap-4">
                        <div class="...">
                            <!--Card 1-->
                            <div class="max-w-lg rounded overflow-hidden shadow-lg">
                                
                                <div class="px-6 py-4">
                                <div class="font-bold text-xl mb-2">{{ $deposit->particulars }}</div>
                                <p class="text-gray-700 text-base">
                                    <div class="grid grid-cols-6 gap-4">
                                       
                                        <div class="col-start-1 col-end-5 ...">Department</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->department }}</div>
                                        <div class="col-start-1 col-end-5 ...">Challan No.</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->challan_number }}</div>

                                        <div class="col-start-1 col-end-5 ...">Date</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->create_date }}</div>
                                        <div class="col-start-1 col-end-5 ...">Challan amount</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->challan_amount }}</div>

                                        <div class="col-start-1 col-end-5 ...">Withdrawn Amount</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->withdrawn_amount }}</div>
                                        
                                        <div class="col-start-1 col-end-5 ...">Balance</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->balance }}</div>

                                        <div class="col-start-1 col-end-5 ...">Treasury</div>
                                        <div class="col-start-7 col-span-5 ...">{{ $deposit->treasury }}</div>
                                    </div>
                                </p>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-span-2 ...">
                            <a class="btn btn-primary btn-sm mb-3 float-right" href="{{ route('withdraws.main.create',$deposit->id) }}">Withdraw</a>
                            <table class="table table-hover table-bordered align-middle">
                                <thead>
                                    <tr>
                                        <th>SI</th>
                                        <th class="w-1/4">Release Memo</th>
                                        <th class="w-1/4">Release Amount</th>
                                        <th class="w-1/4">Release Date</th>
                                       
                                        <th class="w-1/4">Balance</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $i=1
                                    @endphp
                                    
                                        
                                    <tr>
                                        <th scope="row">
                                            @php
                                                echo $i++;
                                            @endphp    
                                        </th>
                                        <td>{{ $withdraw->release_memo }}</td>
                                        <td>{{ $withdraw->release_amount }}</td>
                                        <td>{{ $withdraw->release_date }}</td>
                                       
                                        <td>{{ $withdraw->balance }}</td>
                                        <td >
                                            <div class="grid grid-flow-col md:grid-flow-col">
                                                <div class="...">
                                                    <a type="button" class="btn btn-outline-success btn-sm" href="{{ route('withdraws.edit',$withdraw->id) }}"> 
                                                        <i class="fas fa-pen-square " ></i>
                                                    </a>
                                                </div>
                                                <div class="...">
                                                    <form action="{{ route('withdraws.destroy',$withdraw->id) }}" method="POST" class="ml-2 mr-2">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure?')">
                                                        <i class="fas fa-calendar-times">
                                                        </i>
                                                    </button>
                                                    </form>
                                                   
                                                </div>
                                                <div>
                                                    <a type="button" class="btn btn-outline-success btn-sm" href="{{ route('withdraws.word',$withdraw->id) }}"> 
                                                        <i class="far fa-file-word" > </i>
                                                    </a>
                                                </div>
                                               
                                            </div>
                                            
                                        
                                            
                                            
                                           
                                        </td>
                                    
                                        
                                            
                                    </tr>
                                   
                                    
                                
                                
                                </tbody>
                            </table>
                        </div>
                    </div>    
                    
                </div>  
                
            </div>
        </div>
    </div>
</x-app-layout>